default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bbs_development


test:
  <<: *default
  database: bbs_test

production:
  <<: *default
  database: bbs_production
  username: bbs
  password: <%= ENV['SECONDNET_DATABASE_PASSWORD'] %>